language: python

cache: pip

python:
- '3.6'
- 'nightly'

matrix:
  allow_failures:
  - python: 'nightly'

before_install:
  - sudo apt-get update
  - sudo apt-get install pandoc -y

install:
- make install

script:
- make lint
- make test

deploy:
  provider: pypi
  user: solumilken
  password:
    secure: u4zvuTuu8DJtrZIbM0rwg1QEfTftoW1FstJ3JPO2UDmVU40W4O+5YXlElIkfvz9buYbuDkGCYEVGpQZrPz7CscATLmnzNVV2XL4N2yjjK4Og1YO1o/ctfGuUNxX0XXxuGTRhvddfpLxn+X3dk69bdfGNyZZoQmpPKVUtFMoNsUKzzIiJ7EFVlwttHKSkUTroNg3UtovLwolh2f7bR8UXo49YkRZHyjWn4au0s2ZC3VGwFDxCe8KqgQuVluMydS27YbBNOhoAzu2X1wyxy79iCvRKltIaZLnnKFluaf4Z7MQbbaSXTzwNzywk76pD2q0L0YZP7IKMKIWMY84nWZAD9FEe3CeFtDDl0WoYo5ssWcbT/bEOqUh4qYQO34Smo/WMeK0UZBp7XHLxkIa3MLo3Fsfu5dJYDHPzoUqKdwtIMbgPeSZv/x1FQVRKl5GjmESYI3JY2v5nRmmAEXRbQCGLQfMBMW+GMuPm5hCLZxD/TAMw8xxaIyrQi4awJF2CNI7lHRW/s6Qs/XiEo3DMByBMHH+NhCPhPj7N6Ru0nygboyZaDVhGh0lgeWsXpLwcA5tICtVwhYQwDWIxLi++HVqHMF5MKAULotvtnriPmoiZutGm8+YugaGQDAehvUmJRW71aMaoEQh+SnRH5LmUsYackIrzRAxtGWdkC5qznlsjeUk=
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true

python: 3.6
